/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomBreadcrumb: typeof import('./components/CustomBreadcrumb/CustomBreadcrumb.vue')['default']
    FooterBar: typeof import('./components/FooterBar.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProductCard: typeof import('./components/ProductCard/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
